<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GroupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('groups')->truncate();
        DB::table('groups')->insert([
            [
                'id' => 1,
                'name' => 'Tiểu đội nhóm 1',
                'ward_id' => '1',
                'type' => 'Tiểu đội 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 2,
                'name' => 'Tiểu đội nhóm 2',
                'ward_id' => '4',
                'type' => 'Tiểu đội 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 3,
                'name' => 'Tiểu đội nhóm 3',
                'ward_id' => '6',
                'type' => 'Tiểu đội 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 4,
                'name' => 'Tiểu đội nhóm 4',
                'ward_id' => '7',
                'type' => 'Tiểu đội 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 5,
                'name' => 'Tiểu đội nhóm 5',
                'ward_id' => '8',
                'type' => 'Tiểu đội 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 6,
                'name' => 'Tiểu đội nhóm 6',
                'ward_id' => '10',
                'type' => 'Tiểu đội 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 7,
                'name' => 'Tiểu đội nhóm 7',
                'ward_id' => '13',
                'type' => 'Tiểu đội 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 8,
                'name' => 'Tiểu đội nhóm 8',
                'ward_id' => '16',
                'type' => 'Tiểu đội 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 9,
                'name' => 'Tiểu đội nhóm 9',
                'ward_id' => '19',
                'type' => 'Tiểu đội 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 10,
                'name' => 'Tiểu đội nhóm 10',
                'ward_id' => '22',
                'type' => 'Tiểu đội 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 11,
                'name' => 'Đội 1',
                'ward_id' => '25',
                'type' => 'Sư đoàn 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 12,
                'name' => 'Đội 2',
                'ward_id' => '18',
                'type' => 'Sư đoàn 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 13,
                'name' => 'Đội 3',
                'ward_id' => '28',
                'type' => 'Sư đoàn 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 14,
                'name' => 'Đội 4',
                'ward_id' => '31',
                'type' => 'Sư đoàn 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 15,
                'name' => 'Đội 5',
                'ward_id' => '34',
                'type' => 'Sư đoàn 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 16,
                'name' => 'Đội 6',
                'ward_id' => '37',
                'type' => 'Sư đoàn 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 17,
                'name' => 'Đội 7',
                'ward_id' => '40',
                'type' => 'Sư đoàn 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 18,
                'name' => 'Đội 8',
                'ward_id' => '43',
                'type' => 'Sư đoàn 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 19,
                'name' => 'Đội 9',
                'ward_id' => '46',
                'type' => 'Sư đoàn 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 20,
                'name' => 'Đội 10',
                'ward_id' => '49',
                'type' => 'Sư đoàn 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 21,
                'name' => 'Lữ đoàn nhóm 1',
                'ward_id' => '52',
                'type' => 'Lữ đoàn 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 22,
                'name' => 'Lữ đoàn nhóm 2',
                'ward_id' => '55',
                'type' => 'Lữ đoàn 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 23,
                'name' => 'Lữ đoàn nhóm 3',
                'ward_id' => '58',
                'type' => 'Lữ đoàn 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 24,
                'name' => 'Lữ đoàn nhóm 4',
                'ward_id' => '61',
                'type' => 'Lữ đoàn 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 25,
                'name' => 'Lữ đoàn nhóm 5',
                'ward_id' => '64',
                'type' => 'Lữ đoàn 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 26,
                'name' => 'Lữ đoàn nhóm 6',
                'ward_id' => '67',
                'type' => 'Lữ đoàn 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 27,
                'name' => 'Lữ đoàn nhóm 7',
                'ward_id' => '70',
                'type' => 'Lữ đoàn 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 28,
                'name' => 'Lữ đoàn nhóm 8',
                'ward_id' => '73',
                'type' => 'Lữ đoàn 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 29,
                'name' => 'Lữ đoàn nhóm 9',
                'ward_id' => '76',
                'type' => 'Lữ đoàn 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 30,
                'name' => 'Lữ đoàn nhóm 10',
                'ward_id' => '79',
                'type' => 'Lữ đoàn 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 31,
                'name' => 'Trung đoàn nhóm 1',
                'ward_id' => '82',
                'type' => 'Trung đoàn 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 32,
                'name' => 'Trung đoàn nhóm 2',
                'ward_id' => '85',
                'type' => 'Trung đoàn 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 33,
                'name' => 'Trung đoàn nhóm 3',
                'ward_id' => '88',
                'type' => 'Trung đoàn 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 34,
                'name' => 'Trung đoàn nhóm 4',
                'ward_id' => '91',
                'type' => 'Trung đoàn 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 35,
                'name' => 'Trung đoàn nhóm 5',
                'ward_id' => '94',
                'type' => 'Trung đoàn 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 36,
                'name' => 'Trung đoàn nhóm 6',
                'ward_id' => '97',
                'type' => 'Trung đoàn 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 37,
                'name' => 'Trung đoàn nhóm 7',
                'ward_id' => '100',
                'type' => 'Trung đoàn 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 38,
                'name' => 'Trung đoàn nhóm 8',
                'ward_id' => '103',
                'type' => 'Trung đoàn 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 39,
                'name' => 'Trung đoàn nhóm 9',
                'ward_id' => '106',
                'type' => 'Trung đoàn 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 40,
                'name' => 'Trung đoàn nhóm 10',
                'ward_id' => '109',
                'type' => 'Trung đoàn 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 41,
                'name' => 'Tiểu đoàn nhóm 1',
                'ward_id' => '112',
                'type' => 'Tiểu đoàn 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 42,
                'name' => 'Tiểu đoàn nhóm 2',
                'ward_id' => '115',
                'type' => 'Tiểu đoàn 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 43,
                'name' => 'Tiểu đoàn nhóm 3',
                'ward_id' => '118',
                'type' => 'Tiểu đoàn 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 44,
                'name' => 'Tiểu đoàn nhóm 4',
                'ward_id' => '121',
                'type' => 'Tiểu đoàn 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 45,
                'name' => 'Tiểu đoàn nhóm 5',
                'ward_id' => '124',
                'type' => 'Tiểu đoàn 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 46,
                'name' => 'Tiểu đoàn nhóm 6',
                'ward_id' => '127',
                'type' => 'Tiểu đoàn 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 47,
                'name' => 'Tiểu đoàn nhóm 7',
                'ward_id' => '130',
                'type' => 'Tiểu đoàn 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 48,
                'name' => 'Tiểu đoàn nhóm 8',
                'ward_id' => '133',
                'type' => 'Tiểu đoàn 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 49,
                'name' => 'Tiểu đoàn nhóm 9',
                'ward_id' => '136',
                'type' => 'Tiểu đoàn 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 50,
                'name' => 'Tiểu đoàn nhóm 10',
                'ward_id' => '139',
                'type' => 'Tiểu đoàn 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 51,
                'name' => 'Tiểu đại đội nhóm 1',
                'ward_id' => '142',
                'type' => 'Tiểu đại đội 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 52,
                'name' => 'Tiểu đại đội nhóm 2',
                'ward_id' => '145',
                'type' => 'Tiểu đại đội 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 53,
                'name' => 'Tiểu đại đội nhóm 3',
                'ward_id' => '148',
                'type' => 'Tiểu đại đội 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 54,
                'name' => 'Tiểu đại đội nhóm 4',
                'ward_id' => '151',
                'type' => 'Tiểu đại đội 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 55,
                'name' => 'Tiểu đại đội nhóm 5',
                'ward_id' => '154',
                'type' => 'Tiểu đại đội 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 56,
                'name' => 'Tiểu đại đội nhóm 6',
                'ward_id' => '157',
                'type' => 'Tiểu đại đội 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 57,
                'name' => 'Tiểu đại đội nhóm 7',
                'ward_id' => '160',
                'type' => 'Tiểu đại đội 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 58,
                'name' => 'Tiểu đại đội nhóm 8',
                'ward_id' => '163',
                'type' => 'Tiểu đại đội 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 59,
                'name' => 'Tiểu đại đội nhóm 9',
                'ward_id' => '166',
                'type' => 'Tiểu đại đội 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 60,
                'name' => 'Tiểu đại đội nhóm 10',
                'ward_id' => '169',
                'type' => 'Tiểu đại đội 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 61,
                'name' => 'Liên đoàn nhóm 1',
                'ward_id' => '172',
                'type' => 'Liên đoàn 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 62,
                'name' => 'Liên đoàn nhóm 2',
                'ward_id' => '175',
                'type' => 'Liên đoàn 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 63,
                'name' => 'Liên đoàn nhóm 3',
                'ward_id' => '178',
                'type' => 'Liên đoàn 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 64,
                'name' => 'Liên đoàn nhóm 4',
                'ward_id' => '181',
                'type' => 'Liên đoàn 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 65,
                'name' => 'Liên đoàn nhóm 5',
                'ward_id' => '175',
                'type' => 'Liên đoàn 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 66,
                'name' => 'Liên đoàn nhóm 6',
                'ward_id' => '178',
                'type' => 'Liên đoàn 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 67,
                'name' => 'Liên đoàn nhóm 7',
                'ward_id' => '181',
                'type' => 'Liên đoàn 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 68,
                'name' => 'Liên đoàn nhóm 8',
                'ward_id' => '184',
                'type' => 'Liên đoàn 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 69,
                'name' => 'Liên đoàn nhóm 9',
                'ward_id' => '187',
                'type' => 'Liên đoàn 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 70,
                'name' => 'Liên đoàn nhóm 10',
                'ward_id' => '190',
                'type' => 'Liên đoàn 10 ',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 71,
                'name' => 'Dân đoàn nhóm 1',
                'ward_id' => '193',
                'type' => 'Dân đoàn 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 72,
                'name' => 'Dân đoàn nhóm 2',
                'ward_id' => '196',
                'type' => 'Dân đoàn 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 73,
                'name' => 'Dân đoàn nhóm 3',
                'ward_id' => '199',
                'type' => 'Dân đoàn 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 74,
                'name' => 'Dân đoàn nhóm 4',
                'ward_id' => '202',
                'type' => 'Dân đoàn 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 75,
                'name' => 'Dân đoàn nhóm 5',
                'ward_id' => '205',
                'type' => 'Dân đoàn 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 76,
                'name' => 'Dân đoàn nhóm 6',
                'ward_id' => '208',
                'type' => 'Dân đoàn 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 77,
                'name' => 'Dân đoàn nhóm 7',
                'ward_id' => '211',
                'type' => 'Dân đoàn 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 78,
                'name' => 'Dân đoàn nhóm 8',
                'ward_id' => '214',
                'type' => 'Dân đoàn 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 79,
                'name' => 'Dân đoàn nhóm 9',
                'ward_id' => '217',
                'type' => 'Dân đoàn 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 80,
                'name' => 'Dân đoàn nhóm 10',
                'ward_id' => '220',
                'type' => 'Dân đoàn 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 81,
                'name' => 'Đại đội nhóm 1',
                'ward_id' => '223',
                'type' => 'Đại đội 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 82,
                'name' => 'Đại đội nhóm 2',
                'ward_id' => '226',
                'type' => 'Đại đội 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 83,
                'name' => 'Đại đội nhóm 3',
                'ward_id' => '229',
                'type' => 'Đại đội 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 84,
                'name' => 'Đại đội nhóm 4',
                'ward_id' => '232',
                'type' => 'Đại đội 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 85,
                'name' => 'Đại đội nhóm 5',
                'ward_id' => '235',
                'type' => 'Đại đội 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 86,
                'name' => 'Đại đội nhóm 6',
                'ward_id' => '238',
                'type' => 'Đại đội 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 87,
                'name' => 'Đại đội nhóm 7',
                'ward_id' => '241',
                'type' => 'Đại đội 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 88,
                'name' => 'Đại đội nhóm 8',
                'ward_id' => '244',
                'type' => 'Đại đội 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 89,
                'name' => 'Đại đội nhóm 9',
                'ward_id' => '247',
                'type' => 'Đại đội 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 90,
                'name' => 'Đại đội nhóm 10',
                'ward_id' => '250',
                'type' => 'Đại đội 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 91,
                'name' => 'Trung đội nhóm 1',
                'ward_id' => '253',
                'type' => 'Trung đội 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 92,
                'name' => 'Trung đội nhóm 2',
                'ward_id' => '256',
                'type' => 'Trung đội 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 93,
                'name' => 'Trung đội nhóm 3',
                'ward_id' => '259',
                'type' => 'Trung đội 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 94,
                'name' => 'Trung đội nhóm 4',
                'ward_id' => '262',
                'type' => 'Trung đội 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 95,
                'name' => 'Trung đội nhóm 5',
                'ward_id' => '265',
                'type' => 'Trung đội 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 96,
                'name' => 'Trung đội nhóm 6',
                'ward_id' => '268',
                'type' => 'Trung đội 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 97,
                'name' => 'Trung đội nhóm 7',
                'ward_id' => '271',
                'type' => 'Trung đội 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 98,
                'name' => 'Trung đội nhóm 8',
                'ward_id' => '274',
                'type' => 'Trung đội 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 99,
                'name' => 'Trung đội nhóm 9',
                'ward_id' => '277',
                'type' => 'Trung đội 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 100,
                'name' => 'Trung đội nhóm 10',
                'ward_id' => '280',
                'type' => 'Trung đội 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 101,
                'name' => 'Tiểu đội nhóm 1',
                'ward_id' => '283',
                'type' => 'Tiểu đội 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 102,
                'name' => 'Tiểu đội nhóm 2',
                'ward_id' => '286',
                'type' => 'Tiểu đội 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 103,
                'name' => 'Tiểu đội nhóm 3',
                'ward_id' => '289',
                'type' => 'Tiểu đội 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 104,
                'name' => 'Tiểu đội nhóm 4',
                'ward_id' => '292',
                'type' => 'Tiểu đội 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 105,
                'name' => 'Tiểu đội nhóm 5',
                'ward_id' => '295',
                'type' => 'Tiểu đội 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 106,
                'name' => 'Tiểu đội nhóm 6',
                'ward_id' => '298',
                'type' => 'Tiểu đội 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 107,
                'name' => 'Tiểu đội nhóm 7',
                'ward_id' => '301',
                'type' => 'Tiểu đội 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 108,
                'name' => 'Tiểu đội nhóm 8',
                'ward_id' => '304',
                'type' => 'Tiểu đội 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 109,
                'name' => 'Tiểu đội nhóm 9',
                'ward_id' => '307',
                'type' => 'Tiểu đội 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 110,
                'name' => 'Tiểu đội nhóm 10',
                'ward_id' => '310',
                'type' => 'Tiểu đội 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 111,
                'name' => 'Giao hàng tiết kiệm',
                'ward_id' => '313',
                'type' => 'Giao hàng tiết kiệm',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 112,
                'name' => 'Giao hàng tiết kiệm plus',
                'ward_id' => '316',
                'type' => 'Giao hàng tiết kiệm plus',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 113,
                'name' => 'Giao hàng tiết kiệm sport',
                'ward_id' => '319',
                'type' => 'Giao hàng tiết kiệm sport',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 114,
                'name' => 'Viettel port nhóm 1',
                'ward_id' => '322',
                'type' => 'Viettel port 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 115,
                'name' => 'Viettel port nhóm 2',
                'ward_id' => '325',
                'type' => 'Viettel port 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 116,
                'name' => 'Viettel port nhóm 2',
                'ward_id' => '328',
                'type' => 'Viettel port 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 117,
                'name' => 'Viettel port nhóm 3',
                'ward_id' => '331',
                'type' => 'Viettel port 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 118,
                'name' => 'Viettel port nhóm 4',
                'ward_id' => '334',
                'type' => 'Viettel port 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 119,
                'name' => 'Viettel port nhóm 5',
                'ward_id' => '337',
                'type' => 'Viettel port 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 120,
                'name' => 'Viettel port nhóm 6',
                'ward_id' => '340',
                'type' => 'Viettel port 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 121,
                'name' => 'Giao hàng nhanh nhóm 1',
                'ward_id' => '343',
                'type' => 'Giao hàng nhanh 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 122,
                'name' => 'Giao hàng nhanh nhóm 2',
                'ward_id' => '346',
                'type' => 'Giao hàng nhanh 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 123,
                'name' => 'Giao hàng nhanh nhóm 3',
                'ward_id' => '349',
                'type' => 'Giao hàng nhanh 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 124,
                'name' => 'Giao hàng nhanh nhóm 4',
                'ward_id' => '352',
                'type' => 'Giao hàng nhanh 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 125,
                'name' => 'Giao hàng nhanh nhóm 5',
                'ward_id' => '355',
                'type' => 'Giao hàng nhanh 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 126,
                'name' => 'Giao hàng nhanh nhóm 6',
                'ward_id' => '358',
                'type' => 'Giao hàng nhanh 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 127,
                'name' => 'Giao hàng nhanh nhóm 7',
                'ward_id' => '361',
                'type' => 'Giao hàng nhanh 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 128,
                'name' => 'Giao hàng nhanh nhóm 8',
                'ward_id' => '364',
                'type' => 'Giao hàng nhanh 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 129,
                'name' => 'Giao hàng nhanh nhóm 9',
                'ward_id' => '367',
                'type' => 'Giao hàng nhanh 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 130,
                'name' => 'Giao hàng nhanh nhóm 10',
                'ward_id' => '370',
                'type' => 'Giao hàng nhanh 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 131,
                'name' => 'Quân đoàn nhóm 1',
                'ward_id' => '373',
                'type' => 'Binh đoàn Quyết Thắng 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 132,
                'name' => 'Quân đoàn nhóm 2',
                'ward_id' => '376',
                'type' => 'Binh đoàn Quyết Thắng 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 133,
                'name' => 'Quân đoàn nhóm 3',
                'ward_id' => '379',
                'type' => 'Binh đoàn Quyết Thắng 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 134,
                'name' => 'Quân đoàn nhóm 4',
                'ward_id' => '382',
                'type' => 'Binh đoàn Quyết Thắng 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 135,
                'name' => 'Quân đoàn nhóm 5',
                'ward_id' => '385',
                'type' => 'Binh đoàn Quyết Thắng 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 136,
                'name' => 'Quân đoàn nhóm 6',
                'ward_id' => '388',
                'type' => 'Binh đoàn Quyết Thắng 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 137,
                'name' => 'Quân đoàn nhóm 7',
                'ward_id' => '391',
                'type' => 'Binh đoàn Quyết Thắng 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 138,
                'name' => 'Quân đoàn nhóm 8',
                'ward_id' => '394',
                'type' => 'Binh đoàn Quyết Thắng 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 139,
                'name' => 'Quân đoàn nhóm 9',
                'ward_id' => '397',
                'type' => 'Binh đoàn Quyết Thắng 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 140,
                'name' => 'Quân đoàn nhóm 10',
                'ward_id' => '400',
                'type' => 'Binh đoàn Quyết Thắng 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 141,
                'name' => 'Chiến binh nhóm 1',
                'ward_id' => '403',
                'type' => 'Binh đoàn Hương Giang 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 142,
                'name' => 'Chiến binh nhóm 2',
                'ward_id' => '406',
                'type' => 'Binh đoàn Hương Giang 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 143,
                'name' => 'Chiến binh nhóm 3',
                'ward_id' => '409',
                'type' => 'Binh đoàn Hương Giang 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 144,
                'name' => 'Chiến binh nhóm 4',
                'ward_id' => '412',
                'type' => 'Binh đoàn Hương Giang 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 145,
                'name' => 'Chiến binh nhóm 5',
                'ward_id' => '415',
                'type' => 'Binh đoàn Hương Giang 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 146,
                'name' => 'Chiến binh nhóm 6',
                'ward_id' => '418',
                'type' => 'Binh đoàn Hương Giang 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 147,
                'name' => 'Chiến binh nhóm 7',
                'ward_id' => '421',
                'type' => 'Binh đoàn Hương Giang 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 148,
                'name' => 'Chiến binh nhóm 8',
                'ward_id' => '424',
                'type' => 'Binh đoàn Hương Giang 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 149,
                'name' => 'Chiến binh nhóm 9',
                'ward_id' => '427',
                'type' => 'Binh đoàn Hương Giang 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 150,
                'name' => 'Chiến binh nhóm 10',
                'ward_id' => '430',
                'type' => 'Binh đoàn Hương Giang 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 151,
                'name' => 'Vệ binh nhóm 1',
                'ward_id' => '433',
                'type' => 'Binh đoàn Tây Nguyên 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 152,
                'name' => 'Vệ binh nhóm 2',
                'ward_id' => '436',
                'type' => 'Binh đoàn Tây Nguyên 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 153,
                'name' => 'Vệ binh nhóm 3',
                'ward_id' => '439',
                'type' => 'Binh đoàn Tây Nguyên 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 154,
                'name' => 'Vệ binh nhóm 4',
                'ward_id' => '442',
                'type' => 'Binh đoàn Tây Nguyên 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 155,
                'name' => 'Vệ binh nhóm 5',
                'ward_id' => '445',
                'type' => 'Binh đoàn Tây Nguyên 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 156,
                'name' => 'Vệ binh nhóm 6',
                'ward_id' => '448',
                'type' => 'Binh đoàn Tây Nguyên 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 157,
                'name' => 'Vệ binh nhóm 7',
                'ward_id' => '451',
                'type' => 'Binh đoàn Tây Nguyên 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 158,
                'name' => 'Vệ binh nhóm 8',
                'ward_id' => '454',
                'type' => 'Binh đoàn Tây Nguyên 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 159,
                'name' => 'Vệ binh nhóm 9',
                'ward_id' => '457',
                'type' => 'Binh đoàn Tây Nguyên 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 160,
                'name' => 'Vệ binh nhóm 10',
                'ward_id' => '460',
                'type' => 'Binh đoàn Tây Nguyên 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 161,
                'name' => 'Vinh quang nhóm 1',
                'ward_id' => '463',
                'type' => 'Binh đoàn vinh quang 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 162 ,
                'name' => 'Vinh quang nhóm 2',
                'ward_id' => '466',
                'type' => 'Binh đoàn vinh quang 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 163,
                'name' => 'Vinh quang nhóm 3',
                'ward_id' => '469',
                'type' => 'Binh đoàn vinh quang 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 164,
                'name' => 'Vinh quang nhóm 4',
                'ward_id' => '472',
                'type' => 'Binh đoàn vinh quang 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 165,
                'name' => 'Vinh quang nhóm 5',
                'ward_id' => '475',
                'type' => 'Binh đoàn vinh quang 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 166,
                'name' => 'Vinh quang nhóm 6',
                'ward_id' => '478',
                'type' => 'Binh đoàn vinh quang 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 167,
                'name' => 'Vinh quang nhóm 7',
                'ward_id' => '491',
                'type' => 'Binh đoàn vinh quang 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 168,
                'name' => 'Vinh quang nhóm 8',
                'ward_id' => '494',
                'type' => 'Binh đoàn vinh quang 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 169,
                'name' => 'Vinh quang nhóm 9',
                'ward_id' => '497',
                'type' => 'Binh đoàn vinh quang 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 170,
                'name' => 'Vinh quang nhóm 10',
                'ward_id' => '500',
                'type' => 'Binh đoàn vinh quang 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 171,
                'name' => 'Đại nam nhóm 1',
                'ward_id' => '500',
                'type' => 'Binh đoàn Hà Nội 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 172,
                'name' => 'Đại nam nhóm 2',
                'ward_id' => '503',
                'type' => 'Binh đoàn Hà Nội 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 173,
                'name' => 'Đại nam nhóm 3',
                'ward_id' => '506',
                'type' => 'Binh đoàn Hà Nội 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 174,
                'name' => 'Đại nam nhóm 4',
                'ward_id' => '509',
                'type' => 'Binh đoàn Hà Nội 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 175,
                'name' => 'Đại nam nhóm 5',
                'ward_id' => '512',
                'type' => 'Binh đoàn Hà Nội 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 176,
                'name' => 'Đại nam nhóm 6',
                'ward_id' => '515',
                'type' => 'Binh đoàn Hà Nội 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 177,
                'name' => 'Đại nam nhóm 7',
                'ward_id' => '518',
                'type' => 'Binh đoàn Hà Nội 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 178,
                'name' => 'Đại nam nhóm 8',
                'ward_id' => '521',
                'type' => 'Binh đoàn Hà Nội 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 179,
                'name' => 'Đại nam nhóm 9',
                'ward_id' => '524',
                'type' => 'Binh đoàn Hà Nội 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 180,
                'name' => 'Đại nam nhóm 10',
                'ward_id' => '527',
                'type' => 'Binh đoàn Hà Nội 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 181,
                'name' => 'Phố cổ nhóm 1',
                'ward_id' => '527',
                'type' => 'Binh Đoàn phố cổ 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 182,
                'name' => 'Phố cổ nhóm 2',
                'ward_id' => '530',
                'type' => 'Binh Đoàn phố cổ 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 183,
                'name' => 'Phố cổ nhóm 3',
                'ward_id' => '533',
                'type' => 'Binh Đoàn phố cổ 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 184,
                'name' => 'Phố cổ nhóm 4',
                'ward_id' => '536',
                'type' => 'Binh Đoàn phố cổ 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 185,
                'name' => 'Phố cổ nhóm 5',
                'ward_id' => '539',
                'type' => 'Binh Đoàn phố cổ 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 186,
                'name' => 'Phố cổ nhóm 6',
                'ward_id' => '542',
                'type' => 'Binh Đoàn phố cổ 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 187,
                'name' => 'Phố cổ nhóm 7',
                'ward_id' => '545',
                'type' => 'Binh Đoàn phố cổ 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 188,
                'name' => 'Phố cổ nhóm 8',
                'ward_id' => '548',
                'type' => 'Binh Đoàn phố cổ 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 189,
                'name' => 'Phố cổ nhóm 9',
                'ward_id' => '551',
                'type' => 'Binh Đoàn phố cổ 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 190,
                'name' => 'Phố cổ nhóm 10',
                'ward_id' => '554',
                'type' => 'Binh Đoàn phố cổ 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 191,
                'name' => 'Quân chủng phòng không nhóm 1',
                'ward_id' => '557',
                'type' => 'Tổng Công ty Thành An 1',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 192,
                'name' => 'Quân chủng phòng không nhóm 2',
                'ward_id' => '560',
                'type' => 'Tổng Công ty Thành An 2',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 193,
                'name' => 'Quân chủng phòng không nhóm 3',
                'ward_id' => '563',
                'type' => 'Tổng Công ty Thành An 3',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 194,
                'name' => 'Quân chủng phòng không nhóm 4',
                'ward_id' => '566',
                'type' => 'Tổng Công ty Thành An 4',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 195,
                'name' => 'Quân chủng phòng không nhóm 5',
                'ward_id' => '569',
                'type' => 'Tổng Công ty Thành An 5',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 196,
                'name' => 'Quân chủng phòng không nhóm 6',
                'ward_id' => '572',
                'type' => 'Tổng Công ty Thành An 6',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 197,
                'name' => 'Quân chủng phòng không nhóm 7',
                'ward_id' => '575',
                'type' => 'Tổng Công ty Thành An 7',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 198,
                'name' => 'Quân chủng phòng không nhóm 8',
                'ward_id' => '578',
                'type' => 'Tổng Công ty Thành An 8',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 199,
                'name' => 'Quân chủng phòng không nhóm 9',
                'ward_id' => '581',
                'type' => 'Tổng Công ty Thành An 9',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 200,
                'name' => 'Quân chủng phòng không nhóm 10',
                'ward_id' => '584',
                'type' => 'Tổng Công ty Thành An 10',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
        ]);
    }
}
