<?php

namespace Database\Seeders;

namespace Database\Seeders;

use Faker\Factory as Faker;
use App\Enums\UserRole;
use App\Models\User;
use App\Models\Ward;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('users')->truncate();
        DB::table('users')->insert([
            [
                'id' => 1,
                'first_name' => 'Văn A',
                'last_name' => 'Nguyễn',
                'email' => 'alert.dichohohanoi@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 13,
                'ward_id' => 218,
                'street' => '8 Tôn Thất Thuyết',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 2,
                'first_name' => 'Văn Luyện',
                'last_name' => 'Đào',
                'email' => 'shipper.dichohohanoi@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 13,
                'ward_id' => 218,
                'street' => '49 Ngô Thì Nhậm',
                'phone' => '0912345678',
                'role' => UserRole::SHIPPER,
                'group_id' => 218,
                'position' => 'Hạ sĩ',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 3,
                'first_name' => 'Ngọc Thuận',
                'last_name' => 'Nguyễn',
                'email' => 'nguyenngocthuan@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 3,
                'ward_id' => 43,
                'street' => '39 Hàng Gai',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 4,
                'first_name' => 'Đức Quân',
                'last_name' => 'Đỗ',
                'email' => 'doducquan@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 4,
                'ward_id' => 55,
                'street' => '215 Triều Khúc',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 5,
                'first_name' => 'Thọ Hoàng',
                'last_name' => 'Bùi',
                'email' => 'buithohoang@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 5,
                'ward_id' => 64,
                'street' => '97 Hạo Nam',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 6,
                'first_name' => 'Quỳnh Anh',
                'last_name' => 'Dương',
                'email' => 'duongquynhanh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 6,
                'ward_id' => 67,
                'street' => '65B Hai Bà Trưng',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 7,
                'first_name' => 'Thị Chinh',
                'last_name' => 'Dương',
                'email' => 'duongthichinh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 1,
                'ward_id' => 1,
                'street' => '96 Nguyễn Xiển',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 8,
                'first_name' => 'Hồng Luyến',
                'last_name' => 'Đào',
                'email' => 'daohongluyen@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 7,
                'ward_id' => 76,
                'street' => '402 La Thành',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 9,
                'first_name' => 'Đắc Phương',
                'last_name' => 'Hoàng',
                'email' => 'hoangdacphuong@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 8,
                'ward_id' => 167,
                'street' => '95B Phố Huế',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 10,
                'first_name' => 'Xuân Hinh',
                'last_name' => 'Nguyễn',
                'email' => 'nguyenxuanhinh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 9,
                'ward_id' => 172,
                'street' => '392 Cầu Giấy',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 11,
                'first_name' => 'Cường',
                'last_name' => 'Nguyễn Việt',
                'email' => 'nguyenvietcuong@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 19,
                'ward_id' => 199,
                'street' => '42 Lê Thái Tổ',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 12,
                'first_name' => 'Linh',
                'last_name' => 'Nguyễn Trần Thảo',
                'email' => 'nguyentranthaolinh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 8,
                'ward_id' => 172,
                'street' => '77 Tây Sơn',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 13,
                'first_name' => 'Ngọc',
                'last_name' => 'Nguyễn Bảo',
                'email' => 'nguyenbaongoc@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 10,
                'ward_id' => 199,
                'street' => '158 Thái Hà',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 14,
                'first_name' => 'Bình',
                'last_name' => 'Bùi Thanh',
                'email' => 'buithanhbinh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 18,
                'ward_id' => 64,
                'street' => '164 Nguyễn Tuân',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 15,
                'first_name' => 'Hòa',
                'last_name' => 'Nguyễn Trần Khánh',
                'email' => 'nguyentrankhanhhoa@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 1,
                'ward_id' => 55,
                'street' => '30 Hàng Bông',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 16,
                'first_name' => 'Đức',
                'last_name' => 'Lã Anh',
                'email' => 'laanhduc@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 2,
                'ward_id' => 76,
                'street' => '56 Bạch Thái Bưởi',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 17,
                'first_name' => 'Anh',
                'last_name' => 'Bùi Anh',
                'email' => 'buiduyanh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 20,
                'ward_id' => 26,
                'street' => '15 Trương Định',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 18,
                'first_name' => 'Thắng',
                'last_name' => 'Nguyễn Đức',
                'email' => 'nguyenducthang@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 4,
                'ward_id' => 43,
                'street' => '30 Hoàng Mai',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 19,
                'first_name' => 'Nhật',
                'last_name' => 'Hà Duy',
                'email' => 'haduynhat@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 7,
                'ward_id' => 76,
                'street' => '70 Trần Duy Hưng',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 20,
                'first_name' => 'Thế',
                'last_name' => 'Trần Quang',
                'email' => 'tranquangthe@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 18,
                'ward_id' => 43,
                'street' => '55 Phú Đô',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => null,
                'position' => null,
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],

        ]);
        $faker = Faker::create();
        for ($i = 1; $i <= 579; $i++) {
            $random = random_int(1, 30);
            $last_names = ['Nguyễn', 'Trần', 'Đỗ', 'Trần', 'Bùi', 'Vương', 'Nguyễn', 'Lê', 'Đào', 'Ngô',
                'Nguyễn', 'Trần', 'Đỗ', 'Trần', 'Bùi', 'Vương', 'Nguyễn', 'Lê', 'Đào', 'Ngô',
                'Nguyễn', 'Trần', 'Đỗ', 'Trần', 'Bùi', 'Vương', 'Nguyễn', 'Lê', 'Đào', 'Ngô'];
            $first_names =  ['Nguyễn', 'Trần', 'Đỗ', 'Thọ', 'Bùi', 'Vương', 'Nhật', 'Lê', 'Đào', 'Ngô',
                'Thị', 'Thành', 'Phương', 'Hinh', 'Lâm', 'Lực', 'Điền', 'Hoàng', 'Vũ', 'Hồ',
                'Tùng', 'Cúc', 'Trúc', 'Mai', 'Xuân', 'Hạ', 'Thu', 'Đông', 'Long', 'Lân', 'Quy'
                ];
            User::create(
                [
                    'first_name' => $first_names[random_int(0, 30)] . ' ' . $first_names[random_int(0, 30)],
                    'last_name' => $last_names[random_int(0, 29)],
                    'email' => $faker->email,
                    'password' => Hash::make('123456'),
                    'district_id' => $random,
                    'ward_id' => (Ward::query()->where('district_id', $random)->first())->id,
                    'street' => $i . ' ' . Ward::query()->where('id', $i)->first()->name,
                    'phone' => '0' . random_int(310000000, 999999999),
                    'role' => UserRole::SHIPPER,
                    'group_id' => $i,
                    'position' => 'Hạ sĩ',
                    'created_at' => Carbon::now()->addDays(-$i),
                    'updated_at' => Carbon::now()->addDays(-$i),]
            );
            if (random_int(0, 5) > 3) {
                User::create(
                    [
                        'first_name' => $first_names[random_int(0, 30)] . ' ' . $first_names[random_int(0, 30)],
                        'last_name' => $last_names[random_int(0, 29)],
                        'email' => $faker->email,
                        'password' => Hash::make('123456'),
                        'district_id' => $random,
                        'ward_id' => Ward::query()->where('district_id', $random)->first()->id,
                        'street' => $i . ' ' . Ward::query()->where('id', $i)->first()->name,
                        'phone' => '0' . random_int(310000000, 999999999),
                        'role' => UserRole::SHIPPER,
                        'group_id' => $i,
                        'position' => 'Hạ sĩ',
                        'created_at' => Carbon::now()->addDays(-$i),
                        'updated_at' => Carbon::now()->addDays(-$i),]
                );
            }
        }
    }
}
