<?php

namespace Database\Seeders;

use App\Enums\UserRole;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('users')->truncate();
        DB::table('users')->insert([
            [
                'id' => 1,
                'first_name' => 'admin',
                'last_name' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 19,
                'ward_id' => 626,
                'street' => '8 Tôn Thất Thuyết',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => 1,
                'position' => 'Tiểu đội',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 2,
                'first_name' => 'Chinh',
                'last_name' => 'Dương Thị',
                'email' => 'duongthichinh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 1,
                'ward_id' => 40,
                'street' => '96 Nguyễn Xiển',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => 2,
                'position' => 'Sư đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 3,
                'first_name' => 'Thuận',
                'last_name' => 'Nguyễn Ngọc',
                'email' => 'nguyenngocthuan@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 3,
                'ward_id' => 43,
                'street' => '39 Hàng Gai',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => 3,
                'position' => 'Lữ đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 4,
                'first_name' => 'Quân',
                'last_name' => 'Đỗ Đức',
                'email' => 'doducquan@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 4,
                'ward_id' => 55,
                'street' => '215 Triều Khúc',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => 4,
                'position' => 'Trung đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 5,
                'first_name' => 'Hoàng',
                'last_name' => 'Bùi Thọ',
                'email' => 'buithohoang@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 5,
                'ward_id' => 64,
                'street' => '97 Hạo Nam',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => 5,
                'position' => 'Tiểu đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 6,
                'first_name' => 'Anh',
                'last_name' => 'Dương Quỳnh',
                'email' => 'duongquynhanh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 6,
                'ward_id' => 67,
                'street' => '65B Hai Bà Trưng',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => 6,
                'position' => 'Tiểu đại đội',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 7,
                'first_name' => 'Luyến',
                'last_name' => 'Đào Hồng',
                'email' => 'daohongluyen@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 7,
                'ward_id' => 76,
                'street' => '402 La Thành',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => 7,
                'position' => 'Liên đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 8,
                'first_name' => 'Luyến',
                'last_name' => 'Đào Hồng',
                'email' => 'daohongluyen@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 7,
                'ward_id' => 76,
                'street' => '49 Ngô Thì Nhậm',
                'phone' => '0912345678',
                'role' => UserRole::ADMIN,
                'group_id' => 7,
                'position' => 'Liên đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 9,
                'first_name' => 'Phương',
                'last_name' => 'Hoàng Đắc',
                'email' => 'hoangdacphuong@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 8,
                'ward_id' => 167,
                'street' => '95B Phố Huế',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 8,
                'position' => 'Dân đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 10,
                'first_name' => 'Hinh',
                'last_name' => 'Nguyễn Xuân',
                'email' => 'nguỹenuanhinh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 9,
                'ward_id' => 172,
                'street' => '392 Cầu Giấy',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 9,
                'position' => 'Đại đội',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 11,
                'first_name' => 'Cường',
                'last_name' => 'Nguyễn Việt',
                'email' => 'nguyenvietcuong@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 19,
                'ward_id' => 199,
                'street' => '42 Lê Thái Tổ',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 10,
                'position' => 'Trung đội',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 12,
                'first_name' => 'Linh',
                'last_name' => 'Nguyễn Trần Thảo',
                'email' => 'nguyentranthaolinh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 277,
                'ward_id' => 172,
                'street' => '77 Tây Sơn',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 7,
                'position' => 'Liên đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 13,
                'first_name' => 'Ngọc',
                'last_name' => 'Nguyễn Bảo',
                'email' => 'nguyenbaongoc@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 276,
                'ward_id' => 199,
                'street' => '158 Thái Hà',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 2,
                'position' => 'Sư đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 14,
                'first_name' => 'Bình',
                'last_name' => 'Bùi Thanh',
                'email' => 'buithanhbinh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 273,
                'ward_id' => 64,
                'street' => '164 Nguyễn Tuân',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 11,
                'position' => 'Tiểu đội',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 15,
                'first_name' => 'Hòa',
                'last_name' => 'Nguyễn Trần Khánh',
                'email' => 'nguyentrankhanhhoa@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 268,
                'ward_id' => 55,
                'street' => '30 Hàng Bông',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 4,
                'position' => 'Trung đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 16,
                'first_name' => 'Đức',
                'last_name' => 'Lã Anh',
                'email' => 'laanhduc@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 2,
                'ward_id' => 76,
                'street' => '56 Bạch Thái Bưởi',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 5,
                'position' => 'Tiểu đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 17,
                'first_name' => 'Anh',
                'last_name' => 'Bùi Anh',
                'email' => 'buiduyanh@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 5,
                'ward_id' => 626,
                'street' => '15 Trương Định',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 8,
                'position' => 'Dân đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 18,
                'first_name' => 'Thắng',
                'last_name' => 'Nguyễn Đức',
                'email' => 'nguyenducthang@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 250,
                'ward_id' => 43,
                'street' => '30 Hoàng Mai',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 9,
                'position' => 'Đại đội',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 19,
                'first_name' => 'Nhật',
                'last_name' => 'Hà Duy',
                'email' => 'haduynhat@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 7,
                'ward_id' => 76,
                'street' => '70 Trần Duy Hưng',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 3,
                'position' => 'Lữ đoàn',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
            [
                'id' => 20,
                'first_name' => 'Thế',
                'last_name' => 'Trần Quang',
                'email' => 'tranquangthe@gmail.com',
                'password' => Hash::make('123456'),
                'district_id' => 18,
                'ward_id' => 43,
                'street' => '55 Phú Đô',
                'phone' => '0912345678',
                'role' => UserRole::USER,
                'group_id' => 6,
                'position' => 'Tiểu đại đội',
                'created_at' => Carbon::now()->addDays(-1),
                'updated_at' => Carbon::now()->addDays(-1),
            ],
        ]);
    }
}
