INSERT INTO districts ( maqh,name, type,matp) VALUES  (1, 'Quận Ba Đình', 'Quận', '01'),
 (2, 'Quận Hoàn Kiếm', 'Quận', '01'),
 (3, 'Quận Tây Hồ', 'Quận', '01'),
 (4, 'Quận Long Biên', 'Quận', '01'),
 (5, 'Quận Cầu Giấy', 'Quận', '01'),
 (6, 'Quận Đống Đa', 'Quận', '01'),
 (7, 'Quận Hai Bà Trưng', 'Quận', '01'),
 (8, 'Quận Hoàng Mai', 'Quận', '01'),
 (9, 'Quận Thanh Xuân', 'Quận', '01'),
 (10, 'Huyện Sóc Sơn', 'Huyện', '01'),
 (11, 'Huyện Đông Anh', 'Huyện', '01'),
 (12, 'Huyện Gia Lâm', 'Huyện', '01'),
 (13, 'Quận Nam Từ Liêm', 'Quận', '01'),
 (14, 'Huyện Thanh Trì', 'Huyện', '01'),
 (15, 'Quận Bắc Từ Liêm', 'Quận', '01'),
 (16, 'Huyện Mê Linh', 'Huyện', '01'),
 (17, 'Quận Hà Đông', 'Quận', '01'),
 (18, 'Thị xã Sơn Tây', 'Thị xã', '01'),
 (19, 'Huyện Ba Vì', 'Huyện', '01'),
 (20, 'Huyện Phúc Thọ', 'Huyện', '01'),
 (21, 'Huyện Đan Phượng', 'Huyện', '01'),
 (22, 'Huyện Hoài Đức', 'Huyện', '01'),
 (23, 'Huyện Quốc Oai', 'Huyện', '01'),
 (24, 'Huyện Thạch Thất', 'Huyện', '01'),
 (25, 'Huyện Chương Mỹ', 'Huyện', '01'),
 (26, 'Huyện Thanh Oai', 'Huyện', '01'),
 (27, 'Huyện Thường Tín', 'Huyện', '01'),
 (28, 'Huyện Phú Xuyên', 'Huyện', '01'),
 (29, 'Huyện Ứng Hòa', 'Huyện', '01'),
 (30, 'Huyện Mỹ Đức', 'Huyện', '01');
INSERT INTO wards (name, type, maqh)
VALUES ('Phường Phúc Xá', 'Phường', 1),
       ('Phường Trúc Bạch', 'Phường', 1),
       ('Phường Vĩnh Phúc', 'Phường', 1),
       ('Phường Cống Vị', 'Phường', 1),
       ('Phường Liễu Giai', 'Phường', 1),
       ('Phường Nguyễn Trung Trực', 'Phường', 1),
       ('Phường Quán Thánh', 'Phường', 1),
       ('Phường Ngọc Hà', 'Phường', 1),
       ('Phường Điện Biên', 'Phường', 1),
       ('Phường Đội Cấn', 'Phường', 1),
       ('Phường Ngọc Khánh', 'Phường', 1),
       ('Phường Kim Mã', 'Phường', 1),
       ('Phường Giảng Võ', 'Phường', 1),
       ('Phường Thành Công', 'Phường', 1),
       ('Phường Phúc Tân', 'Phường', 2),
       ('Phường Đồng Xuân', 'Phường', 2),
       ('Phường Hàng Mã', 'Phường', 2),
       ('Phường Hàng Buồm', 'Phường', 2),
       ('Phường Hàng Đào', 'Phường', 2),
       ('Phường Hàng Bồ', 'Phường', 2),
       ('Phường Cửa Đông', 'Phường', 2),
       ('Phường Lý Thái Tổ', 'Phường', 2),
       ('Phường Hàng Bạc', 'Phường', 2),
       ('Phường Hàng Gai', 'Phường', 2),
       ('Phường Chương Dương Độ', 'Phường', 2),
       ('Phường Hàng Trống', 'Phường', 2),
       ('Phường Cửa Nam', 'Phường', 2),
       ('Phường Hàng Bông', 'Phường', 2),
       ('Phường Tràng Tiền', 'Phường', 2),
       ('Phường Trần Hưng Đạo', 'Phường', 2),
       ('Phường Phan Chu Trinh', 'Phường', 2),
       ('Phường Hàng Bài', 'Phường', 2),
       ('Phường Phú Thượng', 'Phường', 3),
       ('Phường Nhật Tân', 'Phường', 3),
       ('Phường Tứ Liên', 'Phường', 3),
       ('Phường Quảng An', 'Phường', 3),
       ('Phường Xuân La', 'Phường', 3),
       ('Phường Yên Phụ', 'Phường', 3),
       ('Phường Bưởi', 'Phường', 3),
       ('Phường Thụy Khuê', 'Phường', 3),
       ('Phường Thượng Thanh', 'Phường', 4),
       ('Phường Ngọc Thụy', 'Phường', 4),
       ('Phường Giang Biên', 'Phường', 4),
       ('Phường Đức Giang', 'Phường', 4),
       ('Phường Việt Hưng', 'Phường', 4),
       ('Phường Gia Thụy', 'Phường', 4),
       ('Phường Ngọc Lâm', 'Phường', 4),
       ('Phường Phúc Lợi', 'Phường', 4),
       ('Phường Bồ Đề', 'Phường', 4),
       ('Phường Sài Đồng', 'Phường', 4),
       ('Phường Long Biên', 'Phường', 4),
       ('Phường Thạch Bàn', 'Phường', 4),
       ('Phường Phúc Đồng', 'Phường', 4),
       ('Phường Cự Khối', 'Phường', 4),
       ('Phường Nghĩa Đô', 'Phường', 5),
       ('Phường Nghĩa Tân', 'Phường', 5),
       ('Phường Mai Dịch', 'Phường', 5),
       ('Phường Dịch Vọng', 'Phường', 5),
       ('Phường Dịch Vọng Hậu', 'Phường', 5),
       ('Phường Quan Hoa', 'Phường', 5),
       ('Phường Yên Hoà', 'Phường', 5),
       ('Phường Trung Hoà', 'Phường', 5),
       ('Phường Cát Linh', 'Phường', 6),
       ('Phường Văn Miếu', 'Phường', 6),
       ('Phường Quốc Tử Giám', 'Phường', 6),
       ('Phường Láng Thượng', 'Phường', 6),
       ('Phường Ô Chợ Dừa', 'Phường', 6),
       ('Phường Văn Chương', 'Phường', 6),
       ('Phường Hàng Bột', 'Phường', 6),
       ('Phường Láng Hạ', 'Phường', 6),
       ('Phường Khâm Thiên', 'Phường', 6),
       ('Phường Thổ Quan', 'Phường', 6),
       ('Phường Nam Đồng', 'Phường', 6),
       ('Phường Trung Phụng', 'Phường', 6),
       ('Phường Quang Trung', 'Phường', 6),
       ('Phường Trung Liệt', 'Phường', 6),
       ('Phường Phương Liên', 'Phường', 6),
       ('Phường Thịnh Quang', 'Phường', 6),
       ('Phường Trung Tự', 'Phường', 6),
       ('Phường Kim Liên', 'Phường', 6),
       ('Phường Phương Mai', 'Phường', 6),
       ('Phường Ngã Tư Sở', 'Phường', 6),
       ('Phường Khương Thượng', 'Phường', 6),
       ('Phường Nguyễn Du', 'Phường', 7),
       ('Phường Bạch Đằng', 'Phường', 7),
       ('Phường Phạm Đình Hổ', 'Phường', 7),
       ('Phường Bùi Thị Xuân', 'Phường', 7),
       ('Phường Ngô Thì Nhậm', 'Phường', 7),
       ('Phường Lê Đại Hành', 'Phường', 7),
       ('Phường Đồng Nhân', 'Phường', 7),
       ('Phường Phố Huế', 'Phường', 7),
       ('Phường Đống Mác', 'Phường', 7),
       ('Phường Thanh Lương', 'Phường', 7),
       ('Phường Thanh Nhàn', 'Phường', 7),
       ('Phường Cầu Dền', 'Phường', 7),
       ('Phường Bách Khoa', 'Phường', 7),
       ('Phường Đồng Tâm', 'Phường', 7),
       ('Phường Vĩnh Tuy', 'Phường', 7),
       ('Phường Bạch Mai', 'Phường', 7),
       ('Phường Quỳnh Mai', 'Phường', 7),
       ('Phường Quỳnh Lôi', 'Phường', 7),
       ('Phường Minh Khai', 'Phường', 7),
       ('Phường Trương Định', 'Phường', 7),
       ('Phường Thanh Trì', 'Phường', 8),
       ('Phường Vĩnh Hưng', 'Phường', 8),
       ('Phường Định Công', 'Phường', 8),
       ('Phường Mai Động', 'Phường', 8),
       ('Phường Tương Mai', 'Phường', 8),
       ('Phường Đại Kim', 'Phường', 8),
       ('Phường Tân Mai', 'Phường', 8),
       ('Phường Hoàng Văn Thụ', 'Phường', 8),
       ('Phường Giáp Bát', 'Phường', 8),
       ('Phường Lĩnh Nam', 'Phường', 8),
       ('Phường Thịnh Liệt', 'Phường', 8),
       ('Phường Trần Phú', 'Phường', 8),
       ('Phường Hoàng Liệt', 'Phường', 8),
       ('Phường Yên Sở', 'Phường', 8),
       ('Phường Nhân Chính', 'Phường', 9),
       ('Phường Thượng Đình', 'Phường', 9),
       ('Phường Khương Trung', 'Phường', 9),
       ('Phường Khương Mai', 'Phường', 9),
       ('Phường Thanh Xuân Trung', 'Phường', 9),
       ('Phường Phương Liệt', 'Phường', 9),
       ('Phường Hạ Đình', 'Phường', 9),
       ('Phường Khương Đình', 'Phường', 9),
       ('Phường Thanh Xuân Bắc', 'Phường', 9),
       ('Phường Thanh Xuân Nam', 'Phường', 9),
       ('Phường Kim Giang', 'Phường', 9),
       ('Thị trấn Sóc Sơn', 'Thị trấn', 10),
       ('Xã Bắc Sơn', 'Xã', 10),
       ('Xã Minh Trí', 'Xã', 10),
       ('Xã Hồng Kỳ', 'Xã', 10),
       ('Xã Nam Sơn', 'Xã', 10),
       ('Xã Trung Giã', 'Xã', 10),
       ('Xã Tân Hưng', 'Xã', 10),
       ('Xã Minh Phú', 'Xã', 10),
       ('Xã Phù Linh', 'Xã', 10),
       ('Xã Bắc Phú', 'Xã', 10),
       ('Xã Tân Minh', 'Xã', 10),
       ('Xã Quang Tiến', 'Xã', 10),
       ('Xã Hiền Ninh', 'Xã', 10),
       ('Xã Tân Dân', 'Xã', 10),
       ('Xã Tiên Dược', 'Xã', 10),
       ('Xã Việt Long', 'Xã', 10),
       ('Xã Xuân Giang', 'Xã', 10),
       ('Xã Mai Đình', 'Xã', 10),
       ('Xã Đức Hoà', 'Xã', 10),
       ('Xã Thanh Xuân', 'Xã', 10),
       ('Xã Đông Xuân', 'Xã', 10),
       ('Xã Kim Lũ', 'Xã', 10),
       ('Xã Phú Cường', 'Xã', 10),
       ('Xã Phú Minh', 'Xã', 10),
       ('Xã Phù Lỗ', 'Xã', 10),
       ('Xã Xuân Thu', 'Xã', 10),
       ('Thị trấn Đông Anh', 'Thị trấn', 11),
       ('Xã Xuân Nộn', 'Xã', 11),
       ('Xã Thuỵ Lâm', 'Xã', 11),
       ('Xã Bắc Hồng', 'Xã', 11),
       ('Xã Nguyên Khê', 'Xã', 11),
       ('Xã Nam Hồng', 'Xã', 11),
       ('Xã Tiên Dương', 'Xã', 11),
       ('Xã Vân Hà', 'Xã', 11),
       ('Xã Uy Nỗ', 'Xã', 11),
       ('Xã Vân Nội', 'Xã', 11),
       ('Xã Liên Hà', 'Xã', 11),
       ('Xã Việt Hùng', 'Xã', 11),
       ('Xã Kim Nỗ', 'Xã', 11),
       ('Xã Kim Chung', 'Xã', 11),
       ('Xã Dục Tú', 'Xã', 11),
       ('Xã Đại Mạch', 'Xã', 11),
       ('Xã Vĩnh Ngọc', 'Xã', 11),
       ('Xã Cổ Loa', 'Xã', 11),
       ('Xã Hải Bối', 'Xã', 11),
       ('Xã Xuân Canh', 'Xã', 11),
       ('Xã Võng La', 'Xã', 11),
       ('Xã Tầm Xá', 'Xã', 11),
       ('Xã Mai Lâm', 'Xã', 11),
       ('Xã Đông Hội', 'Xã', 11),
       ('Thị trấn Yên Viên', 'Thị trấn', 12),
       ('Xã Yên Thường', 'Xã', 12),
       ('Xã Yên Viên', 'Xã', 12),
       ('Xã Ninh Hiệp', 'Xã', 12),
       ('Xã Đình Xuyên', 'Xã', 12),
       ('Xã Dương Hà', 'Xã', 12),
       ('Xã Phù Đổng', 'Xã', 12),
       ('Xã Trung Mầu', 'Xã', 12),
       ('Xã Lệ Chi', 'Xã', 12),
       ('Xã Cổ Bi', 'Xã', 12),
       ('Xã Đặng Xá', 'Xã', 12),
       ('Xã Phú Thị', 'Xã', 12),
       ('Xã Kim Sơn', 'Xã', 12),
       ('Thị trấn Trâu Quỳ', 'Thị trấn', 12),
       ('Xã Dương Quang', 'Xã', 12),
       ('Xã Dương Xá', 'Xã', 12),
       ('Xã Đông Dư', 'Xã', 12),
       ('Xã Đa Tốn', 'Xã', 12),
       ('Xã Kiêu Kỵ', 'Xã', 12),
       ('Xã Bát Tràng', 'Xã', 12),
       ('Xã Kim Lan', 'Xã', 12),
       ('Xã Văn Đức', 'Xã', 12),
       ('Phường Cầu Diễn', 'Phường', 13),
       ('Phường Thượng Cát', 'Phường', 15),
       ('Phường Liên Mạc', 'Phường', 15),
       ('Phường Đông Ngạc', 'Phường', 15),
       ('Phường Đức Thắng', 'Phường', 15),
       ('Phường Thụy Phương', 'Phường', 15),
       ('Phường Tây Tựu', 'Phường', 15),
       ('Phường Xuân Đỉnh', 'Phường', 15),
       ('Phường Xuân Tảo', 'Phường', 15),
       ('Phường Minh Khai', 'Phường', 15),
       ('Phường Cổ Nhuế 1', 'Phường', 15),
       ('Phường Cổ Nhuế 2', 'Phường', 15),
       ('Phường Phú Diễn', 'Phường', 15),
       ('Phường Phúc Diễn', 'Phường', 15),
       ('Phường Xuân Phương', 'Phường', 13),
       ('Phường Phương Canh', 'Phường', 13),
       ('Phường Mỹ Đình 1', 'Phường', 13),
       ('Phường Mỹ Đình 2', 'Phường', 13),
       ('Phường Tây Mỗ', 'Phường', 13),
       ('Phường Mễ Trì', 'Phường', 13),
       ('Phường Phú Đô', 'Phường', 13),
       ('Phường Đại Mỗ', 'Phường', 13),
       ('Phường Trung Văn', 'Phường', 13),
       ('Thị trấn Văn Điển', 'Thị trấn', 14),
       ('Xã Tân Triều', 'Xã', 14),
       ('Xã Thanh Liệt', 'Xã', 14),
       ('Xã Tả Thanh Oai', 'Xã', 14),
       ('Xã Hữu Hoà', 'Xã', 14),
       ('Xã Tam Hiệp', 'Xã', 14),
       ('Xã Tứ Hiệp', 'Xã', 14),
       ('Xã Yên Mỹ', 'Xã', 14),
       ('Xã Vĩnh Quỳnh', 'Xã', 14),
       ('Xã Ngũ Hiệp', 'Xã', 14),
       ('Xã Duyên Hà', 'Xã', 14),
       ('Xã Ngọc Hồi', 'Xã', 14),
       ('Xã Vạn Phúc', 'Xã', 14),
       ('Xã Đại áng', 'Xã', 14),
       ('Xã Liên Ninh', 'Xã', 14),
       ('Xã Đông Mỹ', 'Xã', 14),
       ('Thị trấn Chi Đông', 'Thị trấn', 16),
       ('Xã Đại Thịnh', 'Xã', 16),
       ('Xã Kim Hoa', 'Xã', 16),
       ('Xã Thạch Đà', 'Xã', 16),
       ('Xã Tiến Thắng', 'Xã', 16),
       ('Xã Tự Lập', 'Xã', 16),
       ('Thị trấn Quang Minh', 'Thị trấn', 16),
       ('Xã Thanh Lâm', 'Xã', 16),
       ('Xã Tam Đồng', 'Xã', 16),
       ('Xã Liên Mạc', 'Xã', 16),
       ('Xã Vạn Yên', 'Xã', 16),
       ('Xã Chu Phan', 'Xã', 16),
       ('Xã Tiến Thịnh', 'Xã', 16),
       ('Xã Mê Linh', 'Xã', 16),
       ('Xã Văn Khê', 'Xã', 16),
       ('Xã Hoàng Kim', 'Xã', 16),
       ('Xã Tiền Phong', 'Xã', 16),
       ('Xã Tráng Việt', 'Xã', 16),
       ('Phường Nguyễn Trãi', 'Phường', 17),
       ('Phường Mộ Lao', 'Phường', 17),
       ('Phường Văn Quán', 'Phường', 17),
       ('Phường Vạn Phúc', 'Phường', 17),
       ('Phường Yết Kiêu', 'Phường', 17),
       ('Phường Quang Trung', 'Phường', 17),
       ('Phường La Khê', 'Phường', 17),
       ('Phường Phú La', 'Phường', 17),
       ('Phường Phúc La', 'Phường', 17),
       ('Phường Hà Cầu', 'Phường', 17),
       ('Phường Yên Nghĩa', 'Phường', 17),
       ('Phường Kiến Hưng', 'Phường', 17),
       ('Phường Phú Lãm', 'Phường', 17),
       ('Phường Phú Lương', 'Phường', 17),
       ('Phường Lê Lợi', 'Phường', 18),
       ('Phường Phú Thịnh', 'Phường', 18),
       ('Phường Ngô Quyền', 'Phường', 18),
       ('Phường Quang Trung', 'Phường', 18),
       ('Phường Sơn Lộc', 'Phường', 18),
       ('Phường Xuân Khanh', 'Phường', 18),
       ('Xã Đường Lâm', 'Xã', 18),
       ('Phường Viên Sơn', 'Phường', 18),
       ('Xã Xuân Sơn', 'Xã', 18),
       ('Phường Trung Hưng', 'Phường', 18),
       ('Xã Thanh Mỹ', 'Xã', 18),
       ('Phường Trung Sơn Trầm', 'Phường', 18),
       ('Xã Kim Sơn', 'Xã', 18),
       ('Xã Sơn Đông', 'Xã', 18),
       ('Xã Cổ Đông', 'Xã', 18),
       ('Xã Phú Cường', 'Xã', 19),
       ('Xã Cổ Đô', 'Xã', 19),
       ('Xã Tản Hồng', 'Xã', 19),
       ('Xã Vạn Thắng', 'Xã', 19),
       ('Xã Châu Sơn', 'Xã', 19),
       ('Xã Phong Vân', 'Xã', 19),
       ('Xã Phú Đông', 'Xã', 19),
       ('Xã Phú Phương', 'Xã', 19),
       ('Xã Phú Châu', 'Xã', 19),
       ('Xã Thái Hòa', 'Xã', 19),
       ('Xã Đồng Thái', 'Xã', 19),
       ('Xã Phú Sơn', 'Xã', 19),
       ('Xã Minh Châu', 'Xã', 19),
       ('Xã Vật Lại', 'Xã', 19),
       ('Xã Chu Minh', 'Xã', 19),
       ('Xã Tòng Bạt', 'Xã', 19),
       ('Xã Cẩm Lĩnh', 'Xã', 19),
       ('Xã Sơn Đà', 'Xã', 19),
       ('Xã Đông Quang', 'Xã', 19),
       ('Xã Tiên Phong', 'Xã', 19),
       ('Xã Thụy An', 'Xã', 19),
       ('Xã Cam Thượng', 'Xã', 19),
       ('Xã Thuần Mỹ', 'Xã', 19),
       ('Xã Tản Lĩnh', 'Xã', 19),
       ('Xã Ba Trại', 'Xã', 19),
       ('Xã Minh Quang', 'Xã', 19),
       ('Xã Ba Vì', 'Xã', 19),
       ('Xã Vân Hòa', 'Xã', 19),
       ('Xã Yên Bài', 'Xã', 19),
       ('Xã Khánh Thượng', 'Xã', 19),
       ('Thị trấn Phúc Thọ', 'Thị trấn', 20),
       ('Xã Vân Hà', 'Xã', 20),
       ('Xã Vân Phúc', 'Xã', 20),
       ('Xã Vân Nam', 'Xã', 20),
       ('Xã Xuân Phú', 'Xã', 20),
       ('Xã Phương Độ', 'Xã', 20),
       ('Xã Sen Chiểu', 'Xã', 20),
       ('Xã Cẩm Đình', 'Xã', 20),
       ('Xã Võng Xuyên', 'Xã', 20),
       ('Xã Thọ Lộc', 'Xã', 20),
       ('Xã Long Xuyên', 'Xã', 20),
       ('Xã Thượng Cốc', 'Xã', 20),
       ('Xã Hát Môn', 'Xã', 20),
       ('Xã Tích Giang', 'Xã', 20),
       ('Xã Thanh Đa', 'Xã', 20),
       ('Xã Trạch Mỹ Lộc', 'Xã', 20),
       ('Xã Phúc Hòa', 'Xã', 20),
       ('Xã Ngọc Tảo', 'Xã', 20),
       ('Xã Phụng Thượng', 'Xã', 20),
       ('Xã Tam Thuấn', 'Xã', 20),
       ('Xã Tam Hiệp', 'Xã', 20),
       ('Xã Hiệp Thuận', 'Xã', 20),
       ('Xã Liên Hiệp', 'Xã', 20),
       ('Thị trấn Phùng', 'Thị trấn', 21),
       ('Xã Trung Châu', 'Xã', 21),
       ('Xã Thọ An', 'Xã', 21),
       ('Xã Thọ Xuân', 'Xã', 21),
       ('Xã Hồng Hà', 'Xã', 21),
       ('Xã Liên Hồng', 'Xã', 21),
       ('Xã Liên Hà', 'Xã', 21),
       ('Xã Hạ Mỗ', 'Xã', 21),
       ('Xã Liên Trung', 'Xã', 21),
       ('Xã Phương Đình', 'Xã', 21),
       ('Xã Thượng Mỗ', 'Xã', 21),
       ('Xã Tân Hội', 'Xã', 21),
       ('Xã Tân Lập', 'Xã', 21),
       ('Xã Đan Phượng', 'Xã', 21),
       ('Xã Đồng Tháp', 'Xã', 21),
       ('Xã Song Phượng', 'Xã', 21),
       ('Thị trấn Trạm Trôi', 'Thị trấn', 22),
       ('Xã Đức Thượng', 'Xã', 22),
       ('Xã Minh Khai', 'Xã', 22),
       ('Xã Dương Liễu', 'Xã', 22),
       ('Xã Di Trạch', 'Xã', 22),
       ('Xã Đức Giang', 'Xã', 22),
       ('Xã Cát Quế', 'Xã', 22),
       ('Xã Kim Chung', 'Xã', 22),
       ('Xã Yên Sở', 'Xã', 22),
       ('Xã Sơn Đồng', 'Xã', 22),
       ('Xã Vân Canh', 'Xã', 22),
       ('Xã Đắc Sở', 'Xã', 22),
       ('Xã Lại Yên', 'Xã', 22),
       ('Xã Tiền Yên', 'Xã', 22),
       ('Xã Song Phương', 'Xã', 22),
       ('Xã An Khánh', 'Xã', 22),
       ('Xã An Thượng', 'Xã', 22),
       ('Xã Vân Côn', 'Xã', 22),
       ('Phường Dương Nội', 'Phường', 17),
       ('Xã La Phù', 'Xã', 22),
       ('Xã Đông La', 'Xã', 22),
       ('Thị trấn Quốc Oai', 'Thị trấn', 23),
       ('Xã Sài Sơn', 'Xã', 23),
       ('Xã Phượng Cách', 'Xã', 23),
       ('Xã Yên Sơn', 'Xã', 23),
       ('Xã Ngọc Liệp', 'Xã', 23),
       ('Xã Ngọc Mỹ', 'Xã', 23),
       ('Xã Liệp Tuyết', 'Xã', 23),
       ('Xã Thạch Thán', 'Xã', 23),
       ('Xã Đồng Quang', 'Xã', 23),
       ('Xã Phú Cát', 'Xã', 23),
       ('Xã Tuyết Nghĩa', 'Xã', 23),
       ('Xã Nghĩa Hương', 'Xã', 23),
       ('Xã Cộng Hòa', 'Xã', 23),
       ('Xã Tân Phú', 'Xã', 23),
       ('Xã Đại Thành', 'Xã', 23),
       ('Xã Phú Mãn', 'Xã', 23),
       ('Xã Cấn Hữu', 'Xã', 23),
       ('Xã Tân Hòa', 'Xã', 23),
       ('Xã Hòa Thạch', 'Xã', 23),
       ('Xã Đông Yên', 'Xã', 23),
       ('Thị trấn Liên Quan', 'Thị trấn', 24),
       ('Xã Đại Đồng', 'Xã', 24),
       ('Xã Cẩm Yên', 'Xã', 24),
       ('Xã Lại Thượng', 'Xã', 24),
       ('Xã Phú Kim', 'Xã', 24),
       ('Xã Hương Ngải', 'Xã', 24),
       ('Xã Canh Nậu', 'Xã', 24),
       ('Xã Kim Quan', 'Xã', 24),
       ('Xã Dị Nậu', 'Xã', 24),
       ('Xã Bình Yên', 'Xã', 24),
       ('Xã Chàng Sơn', 'Xã', 24),
       ('Xã Thạch Hoà', 'Xã', 24),
       ('Xã Cần Kiệm', 'Xã', 24),
       ('Xã Hữu Bằng', 'Xã', 24),
       ('Xã Phùng Xá', 'Xã', 24),
       ('Xã Tân Xã', 'Xã', 24),
       ('Xã Thạch Xá', 'Xã', 24),
       ('Xã Bình Phú', 'Xã', 24),
       ('Xã Hạ Bằng', 'Xã', 24),
       ('Xã Đồng Trúc', 'Xã', 24),
       ('Thị trấn Chúc Sơn', 'Thị trấn', 25),
       ('Thị trấn Xuân Mai', 'Thị trấn', 25),
       ('Xã Phụng Châu', 'Xã', 25),
       ('Xã Tiên Phương', 'Xã', 25),
       ('Xã Đông Sơn', 'Xã', 25),
       ('Xã Đông Phương Yên', 'Xã', 25),
       ('Xã Phú Nghĩa', 'Xã', 25),
       ('Xã Trường Yên', 'Xã', 25),
       ('Xã Ngọc Hòa', 'Xã', 25),
       ('Xã Thủy Xuân Tiên', 'Xã', 25),
       ('Xã Thanh Bình', 'Xã', 25),
       ('Xã Trung Hòa', 'Xã', 25),
       ('Xã Đại Yên', 'Xã', 25),
       ('Xã Thụy Hương', 'Xã', 25),
       ('Xã Tốt Động', 'Xã', 25),
       ('Xã Lam Điền', 'Xã', 25),
       ('Xã Tân Tiến', 'Xã', 25),
       ('Xã Nam Phương Tiến', 'Xã', 25),
       ('Xã Hợp Đồng', 'Xã', 25),
       ('Xã Hoàng Văn Thụ', 'Xã', 25),
       ('Xã Hoàng Diệu', 'Xã', 25),
       ('Xã Hữu Văn', 'Xã', 25),
       ('Xã Quảng Bị', 'Xã', 25),
       ('Xã Mỹ Lương', 'Xã', 25),
       ('Xã Thượng Vực', 'Xã', 25),
       ('Xã Hồng Phong', 'Xã', 25),
       ('Xã Đồng Phú', 'Xã', 25),
       ('Xã Trần Phú', 'Xã', 25),
       ('Xã Văn Võ', 'Xã', 25),
       ('Xã Đồng Lạc', 'Xã', 25),
       ('Xã Hòa Chính', 'Xã', 25),
       ('Xã Phú Nam An', 'Xã', 25),
       ('Thị trấn Kim Bài', 'Thị trấn', 26),
       ('Phường Đồng Mai', 'Phường', 17),
       ('Xã Cự Khê', 'Xã', 26),
       ('Phường Biên Giang', 'Phường', 17),
       ('Xã Bích Hòa', 'Xã', 26),
       ('Xã Mỹ Hưng', 'Xã', 26),
       ('Xã Cao Viên', 'Xã', 26),
       ('Xã Bình Minh', 'Xã', 26),
       ('Xã Tam Hưng', 'Xã', 26),
       ('Xã Thanh Cao', 'Xã', 26),
       ('Xã Thanh Thùy', 'Xã', 26),
       ('Xã Thanh Mai', 'Xã', 26),
       ('Xã Thanh Văn', 'Xã', 26),
       ('Xã Đỗ Động', 'Xã', 26),
       ('Xã Kim An', 'Xã', 26),
       ('Xã Kim Thư', 'Xã', 26),
       ('Xã Phương Trung', 'Xã', 26),
       ('Xã Tân Ước', 'Xã', 26),
       ('Xã Dân Hòa', 'Xã', 26),
       ('Xã Liên Châu', 'Xã', 26),
       ('Xã Cao Dương', 'Xã', 26),
       ('Xã Xuân Dương', 'Xã', 26),
       ('Xã Hồng Dương', 'Xã', 26),
       ('Thị trấn Thường Tín', 'Thị trấn', 27),
       ('Xã Ninh Sở', 'Xã', 27),
       ('Xã Nhị Khê', 'Xã', 27),
       ('Xã Duyên Thái', 'Xã', 27),
       ('Xã Khánh Hà', 'Xã', 27),
       ('Xã Hòa Bình', 'Xã', 27),
       ('Xã Văn Bình', 'Xã', 27),
       ('Xã Hiền Giang', 'Xã', 27),
       ('Xã Hồng Vân', 'Xã', 27),
       ('Xã Vân Tảo', 'Xã', 27),
       ('Xã Liên Phương', 'Xã', 27),
       ('Xã Văn Phú', 'Xã', 27),
       ('Xã Tự Nhiên', 'Xã', 27),
       ('Xã Tiền Phong', 'Xã', 27),
       ('Xã Hà Hồi', 'Xã', 27),
       ('Xã Thư Phú', 'Xã', 27),
       ('Xã Nguyễn Trãi', 'Xã', 27),
       ('Xã Quất Động', 'Xã', 27),
       ('Xã Chương Dương', 'Xã', 27),
       ('Xã Tân Minh', 'Xã', 27),
       ('Xã Lê Lợi', 'Xã', 27),
       ('Xã Thắng Lợi', 'Xã', 27),
       ('Xã Dũng Tiến', 'Xã', 27),
       ('Xã Thống Nhất', 'Xã', 27),
       ('Xã Nghiêm Xuyên', 'Xã', 27),
       ('Xã Tô Hiệu', 'Xã', 27),
       ('Xã Văn Tự', 'Xã', 27),
       ('Xã Vạn Điểm', 'Xã', 27),
       ('Xã Minh Cường', 'Xã', 27),
       ('Thị trấn Phú Minh', 'Thị trấn', 28),
       ('Thị trấn Phú Xuyên', 'Thị trấn', 28),
       ('Xã Hồng Minh', 'Xã', 28),
       ('Xã Phượng Dực', 'Xã', 28),
       ('Xã Văn Nhân', 'Xã', 28),
       ('Xã Thụy Phú', 'Xã', 28),
       ('Xã Tri Trung', 'Xã', 28),
       ('Xã Đại Thắng', 'Xã', 28),
       ('Xã Phú Túc', 'Xã', 28),
       ('Xã Văn Hoàng', 'Xã', 28),
       ('Xã Hồng Thái', 'Xã', 28),
       ('Xã Hoàng Long', 'Xã', 28),
       ('Xã Quang Trung', 'Xã', 28),
       ('Xã Nam Phong', 'Xã', 28),
       ('Xã Nam Triều', 'Xã', 28),
       ('Xã Tân Dân', 'Xã', 28),
       ('Xã Sơn Hà', 'Xã', 28),
       ('Xã Chuyên Mỹ', 'Xã', 28),
       ('Xã Khai Thái', 'Xã', 28),
       ('Xã Phúc Tiến', 'Xã', 28),
       ('Xã Vân Từ', 'Xã', 28),
       ('Xã Tri Thủy', 'Xã', 28),
       ('Xã Đại Xuyên', 'Xã', 28),
       ('Xã Phú Yên', 'Xã', 28),
       ('Xã Bạch Hạ', 'Xã', 28),
       ('Xã Quang Lãng', 'Xã', 28),
       ('Xã Châu Can', 'Xã', 28),
       ('Xã Minh Tân', 'Xã', 28),
       ('Thị trấn Vân Đình', 'Thị trấn', 29),
       ('Xã Viên An', 'Xã', 29),
       ('Xã Viên Nội', 'Xã', 29),
       ('Xã Hoa Sơn', 'Xã', 29),
       ('Xã Quảng Phú Cầu', 'Xã', 29),
       ('Xã Trường Thịnh', 'Xã', 29),
       ('Xã Cao Thành', 'Xã', 29),
       ('Xã Liên Bạt', 'Xã', 29),
       ('Xã Sơn Công', 'Xã', 29),
       ('Xã Đồng Tiến', 'Xã', 29),
       ('Xã Phương Tú', 'Xã', 29),
       ('Xã Trung Tú', 'Xã', 29),
       ('Xã Đồng Tân', 'Xã', 29),
       ('Xã Tảo Dương Văn', 'Xã', 29),
       ('Xã Vạn Thái', 'Xã', 29),
       ('Xã Minh Đức', 'Xã', 29),
       ('Xã Hòa Lâm', 'Xã', 29),
       ('Xã Hòa Xá', 'Xã', 29),
       ('Xã Trầm Lộng', 'Xã', 29),
       ('Xã Kim Đường', 'Xã', 29),
       ('Xã Hòa Nam', 'Xã', 29),
       ('Xã Hòa Phú', 'Xã', 29),
       ('Xã Đội Bình', 'Xã', 29),
       ('Xã Đại Hùng', 'Xã', 29),
       ('Xã Đông Lỗ', 'Xã', 29),
       ('Xã Phù Lưu', 'Xã', 29),
       ('Xã Đại Cường', 'Xã', 29),
       ('Xã Lưu Hoàng', 'Xã', 29),
       ('Xã Hồng Quang', 'Xã', 29),
       ('Thị trấn Đại Nghĩa', 'Thị trấn', 30),
       ('Xã Đồng Tâm', 'Xã', 30),
       ('Xã Thượng Lâm', 'Xã', 30),
       ('Xã Tuy Lai', 'Xã', 30),
       ('Xã Phúc Lâm', 'Xã', 30),
       ('Xã Mỹ Thành', 'Xã', 30),
       ('Xã Bột Xuyên', 'Xã', 30),
       ('Xã An Mỹ', 'Xã', 30),
       ('Xã Hồng Sơn', 'Xã', 30),
       ('Xã Lê Thanh', 'Xã', 30),
       ('Xã Xuy Xá', 'Xã', 30),
       ('Xã Phùng Xá', 'Xã', 30),
       ('Xã Phù Lưu Tế', 'Xã', 30),
       ('Xã Đại Hưng', 'Xã', 30),
       ('Xã Vạn Kim', 'Xã', 30),
       ('Xã Đốc Tín', 'Xã', 30),
       ('Xã Hương Sơn', 'Xã', 30),
       ('Xã Hùng Tiến', 'Xã', 30),
       ('Xã An Tiến', 'Xã', 30),
       ('Xã Hợp Tiến', 'Xã', 30),
       ('Xã Hợp Thanh', 'Xã', 30),
       ('Xã An Phú', 'Xã', 30) ;
